services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5550:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
